"""Templates de prompts para el sistema."""

from .templates import (
    PARSE_OFFER_PROMPT,
    EVALUATE_CV_PROMPT,
    INTERVIEW_QUESTION_PROMPT,
    EVALUATE_ANSWER_PROMPT,
    GENERATE_GREETING_PROMPT,
    GENERATE_FAREWELL_PROMPT,
)

__all__ = [
    "PARSE_OFFER_PROMPT",
    "EVALUATE_CV_PROMPT",
    "INTERVIEW_QUESTION_PROMPT",
    "EVALUATE_ANSWER_PROMPT",
    "GENERATE_GREETING_PROMPT",
    "GENERATE_FAREWELL_PROMPT",
]
